## Hypothesis Testing

## Z - Test

In [42]:
#NUll hypothesis(H0) = The mean weekly operating cost is still described by the theoretical model: 
#Alternative hypothesis(HA) = the mean weekly operating cost is higher than the theoretical model expected:

In [43]:
#xbar= 3050 , popmean = 4000 (1000 + 5(600units), stddev = 125 , n = 25(retaraunts) 

In [44]:
#As this is normal distribution we can go to the tstats value to check
#tstats formula = samplemean - popmean/(stddev/sqrt(n))

In [45]:
import math
import scipy.stats as stats
import numpy as np

In [46]:
xbar = 3050
popmean = 600
stddev = 125
n = 25

In [49]:
z_score = (xbar-popmean)/stddev
z_score

19.6

In [40]:
#critical value
critical_z_value=stats.norm.ppf(1-0.05)
critical_z_value

1.6448536269514722

In [50]:
if z_score > critical_z_value:
    print("Reject Null Hypothesis. There is evidence to support the claim that the weekly operating costs have increased.")
else:
    print("Fail to reject Null Hypothesis. There is not enough evidence to support the claim that the weekly operating costs have increased.")


Reject Null Hypothesis. There is evidence to support the claim that the weekly operating costs have increased.


## CHI-SQUARE TEST

In [58]:
import pandas as pd

i have done two methods in the chisquare test as the first method is to make csv file from the data and import it to the jupytor note book and perform chisqare test
and another method is to calculate and do the test
first method is here

In [65]:
data = pd.read_csv('Mizzarecorp.csv',index_col="Satisfaction")

In [66]:
data

Smart_Thermostat  Smart_Light
Satisfaction                                   
Very Satisfied                  50           70
Satisfied                       80          100
Neutral                         60           90
Unsatisfied                     30           50
Very Unsatisfied                20           50

Null Hypothesis (H0): There is no association between the type of smart home device purchased and the customer satisfaction level.

Alternative Hypothesis (H1): There is an association between the type of smart home device purchased and the customer satisfaction level.

In [83]:
#stats value from the inbuilt python funtion
#the formula is chi2 = (expected value - observed value)wholesquare/expectedvalue
stats.chi2_contingency(data)

(5.638227513227513,
 0.22784371130697179,
 4,
 array([[ 48.,  72.],
        [ 72., 108.],
        [ 60.,  90.],
        [ 32.,  48.],
        [ 28.,  42.]]))

In [84]:
#2nd method of chisqare test

In [85]:
#observed values of Smart Thermo and smart light
observed = np.array([[50, 70],
                     [80, 100],
                     [60, 90],
                     [30, 50],
                     [20, 50]])
observed

array([[ 50,  70],
       [ 80, 100],
       [ 60,  90],
       [ 30,  50],
       [ 20,  50]])

In [86]:
#calculated expected values of thermo and smart light
# to calculate expected  E = rowcounts*columncounts/totalcount
expected = np.array([[48,72],
                    [72,108],
                    [60,90],
                    [32,48],
                    [28,42]])
expected

array([[ 48,  72],
       [ 72, 108],
       [ 60,  90],
       [ 32,  48],
       [ 28,  42]])

In [87]:
stats.chisquare(expected,observed)

Power_divergenceResult(statistic=array([4.21333333, 2.05714286]), pvalue=array([0.37790353, 0.72524945]))

In [88]:
stats.chi2.ppf(1-0.05,4)

9.487729036781154

In [82]:
#since the stats value is not higher than the critical value 
# we failed to reject the null hopothisis
#There is no association between the type of smart home device purchased and the customer satisfaction level.